DATA:
  DATASET_NAME: mnist
  TRAIN_SIZE: 256
  TEST_SIZE: 64
  N_CLASSES: 10
  TARGET_CLASSES: null
  FLATTEN: true
  NORMALIZE: true
  SAVE_DIR: datasets
  USE_NPZ: true

MODEL:
  N_LAYERS: 3
  N_WIDTH: 1024
  WEIGHT_VARIANCE: 2.0
  BIAS_VARIANCE: 0.0

OPTIMIZER:
  BATCH_SIZE: 128
  LEARNING_RATE: 0.1
  DAMPING: 0.0
  DIAG_REG: 0.0

GENERAL:
  SEED: 47
  EPOCHS: 10
  DEVICES: 1
  STORE_ON_DEVICE: false
  