DATA:
  DATASET_NAME: mnist
  TRAIN_SIZE: 128
  TEST_SIZE: 32
  N_CLASSES: 2
  TARGET_CLASSES: [1,7]
  FLATTEN: true
  NORMALIZE: true
  SAVE_DIR: datasets

MODEL:
  N_LAYERS: 3
  N_WIDTH: 2048
  WEIGHT_VARIANCE: 2.0
  BIAS_VARIANCE: 0.0

OPTIMIZER:
  BATCH_SIZE: 128
  LEARNING_RATE: 0.1

GENERAL:
  SEED: 47
  EPOCHS: 5
  DEVICES: 0