DATA:
  DATASET_NAME: fashion_mnist
  TRAIN_SIZE: 60000
  TEST_SIZE: 10000
  N_CLASSES: 10
  TARGET_CLASSES: null
  FLATTEN: true
  NORMALIZE: true
  SAVE_DIR: datasets
  USE_NPZ: true

MODEL:
  N_LAYERS: 3
  N_WIDTH: 1024
  WEIGHT_VARIANCE: 2.0
  BIAS_VARIANCE: 0.0

OPTIMIZER:
  BATCH_SIZE: 128
  LEARNING_RATE: 0.05
  NTKS: afa # afa(all_for_all), ofa(one_for_all), ofe(one_for_epoch)

GENERAL:
  SEED: 47
  EPOCHS: 10
  DEVICES: 1